use ratatui::text::Line;

pub fn transform_digit_to_ascii(digit: i32) -> Vec<ratatui::text::Line<'static>> {
    match digit { 
        0 =>   vec![Line::from("┌────────┐"),
                    Line::from("│        │"),
                    Line::from("│ ┌────┐ │"),
                    Line::from("│ │    │ │"),
                    Line::from("│ │    │ │"),
                    Line::from("│ │    │ │"),
                    Line::from("│ │    │ │"),
                    Line::from("│ │    │ │"),
                    Line::from("│ └────┘ │"),
                    Line::from("│        │"),
                    Line::from("└────────┘")],
        1 =>   vec![Line::from("   ┌──┐   "),
                    Line::from("   │  │   "),
                    Line::from("   │  │   "),
                    Line::from("   │  │   "),
                    Line::from("   │  │   "),
                    Line::from("   │  │   "),
                    Line::from("   │  │   "),
                    Line::from("   │  │   "),
                    Line::from("   │  │   "),
                    Line::from("   │  │   "),
                    Line::from("   └──┘   ")],
        2 =>   vec![Line::from("┌────────┐"),
                    Line::from("│        │"),
                    Line::from("└────┐   │"),
                    Line::from("     │   │"),
                    Line::from("┌────┘   │"),
                    Line::from("│        │"),
                    Line::from("│   ┌────┘"),
                    Line::from("│   │     "),
                    Line::from("│   └────┐"),
                    Line::from("│        │"),
                    Line::from("└────────┘")],
        3 =>   vec![Line::from("┌────────┐"),
                    Line::from("│        │"),
                    Line::from("└────┐   │"),
                    Line::from("     │   │"),
                    Line::from("┌────┘   │"),
                    Line::from("│        │"),
                    Line::from("└────┐   │"),
                    Line::from("     │   │"),
                    Line::from("┌────┘   │"),
                    Line::from("│        │"),
                    Line::from("└────────┘")],
        4 =>   vec![Line::from("┌──┐      "),
                    Line::from("│  │      "),
                    Line::from("│  │      "),
                    Line::from("│  │      "),
                    Line::from("│  │  ┌──┐"),
                    Line::from("│  │  │  │"),
                    Line::from("│  └──┘  │"),
                    Line::from("│        │"),
                    Line::from("└─────┐  │"),
                    Line::from("      │  │"),
                    Line::from("      └──┘")],
        5 =>   vec![Line::from("┌────────┐"),
                    Line::from("│        │"),
                    Line::from("│   ┌────┘"),
                    Line::from("│   │     "),
                    Line::from("│   └────┐"),
                    Line::from("│        │"),
                    Line::from("└────┐   │"),
                    Line::from("     │   │"),
                    Line::from("┌────┘   │"),
                    Line::from("│        │"),
                    Line::from("└────────┘")],
        6 =>   vec![Line::from("┌────────┐"),
                    Line::from("│        │"),
                    Line::from("│   ┌────┘"),
                    Line::from("│   │     "),
                    Line::from("│   └────┐"),
                    Line::from("│        │"),
                    Line::from("│ ┌────┐ │"),
                    Line::from("│ │    │ │"),
                    Line::from("│ └────┘ │"),
                    Line::from("│        │"),
                    Line::from("└────────┘")],
        7 =>   vec![Line::from("┌────────┐"),
                    Line::from("│        │"),
                    Line::from("└────┐   │"),
                    Line::from("     │   │"),
                    Line::from("     │   │"),
                    Line::from("     │   │"),
                    Line::from("     │   │"),
                    Line::from("     │   │"),
                    Line::from("     │   │"),
                    Line::from("     │   │"),
                    Line::from("     └───┘")],
        8 =>   vec![Line::from("┌────────┐"),
                    Line::from("│        │"),
                    Line::from("│ ┌────┐ │"),
                    Line::from("│ │    │ │"),
                    Line::from("│ └────┘ │"),
                    Line::from("│        │"),
                    Line::from("│ ┌────┐ │"),
                    Line::from("│ │    │ │"),
                    Line::from("│ └────┘ │"),
                    Line::from("│        │"),
                    Line::from("└────────┘")],
        9 =>   vec![Line::from("┌────────┐"),
                    Line::from("│        │"),
                    Line::from("│ ┌────┐ │"),
                    Line::from("│ │    │ │"),
                    Line::from("│ └────┘ │"),
                    Line::from("│        │"),
                    Line::from("└────┐   │"),
                    Line::from("     │   │"),
                    Line::from("┌────┘   │"),
                    Line::from("│        │"),
                    Line::from("└────────┘")],
        _ =>   vec![Line::from("")],
        
    }
}

pub fn draw_colon() -> Vec<ratatui::text::Line<'static>> {
        vec![Line::from("        "),
             Line::from("        "),
             Line::from("        "),
             Line::from(" ┌────┐ "),
             Line::from(" │    │ "),
             Line::from(" └────┘ "),
             Line::from("        "),
             Line::from(" ┌────┐ "),
             Line::from(" │    │ "),
             Line::from(" └────┘ "),
             Line::from("        "),
             Line::from("        ")]
}

